### ISSUE TITLE
Cannot modify tridas object location information in metadata browser.

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/tellervo#44] opened 2015-12-20 05:22 UTC
I have a newly created object in my tridas server. I open the metadata browser, select my object and edit location data. Location entry appears to save and load correctly until I reload the object, which shows that no location data has actually been saved.

**Comment by petebrew** [comment] 2016-01-22 18:27
Duplicate of Bug #8

**Closed by petebrew** 2016-01-22 18:27 UTC
Labels: duplicate
